@baseUrl = https://8080-marcossakaguchi-atvapi1-e9qmecxwmn2.ws-us115.gitpod.io

###

GET {{baseUrl}}/tarefa

###


GET {{baseUrl}}/tarefa/3


###

POST {{baseUrl}}/tarefa
Content-type: application/json

{
    "descricao":"manbre 85",
    "concluido":true
}


###


PUT {{baseUrl}}/tarefa/4
Content-type: application/json

{
    "descricao":"rogerio",
    "concluido":false
}
###

DELETE {{baseUrl}}/tarefa/2